# Site settings
title: 159 Photography
email: info@159photography.co.uk
email-title: Email 159 photography for a chat
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.159photography.co.uk" # the base hostname & protocol for your site
url.title: "159 Photography"
sitelogo: images/logo-159photography-white.png
mobile: 07581 739340
mobile-title: Call 159 photography today

### Social Media
twitter_username: https://twitter.com/159photography1
follow-tw-title: Follow 159 Photography on Twitter
instagram_username: https://www.instagram.com/onefiveninephotography/
follow-in-title: Follow 159 Photography on Instagram
facebook_username: https://www.facebook.com/159photography/
follow-fb-title: Follow 159 Photography on Facebook

favicon: images/logo.jpg

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

INSTAGRAM_USER_ID: photomattphoto
INSTAGRAM_CLIENT_ID: 52dbe75f408d4e43923272ff63fe64b2